# Generated by Django 2.2.7 on 2019-11-28 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='category_images')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_description', models.TextField(max_length=255)),
                ('sort_description', models.TextField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='product_images')),
                ('price', models.IntegerField()),
                ('special_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=100)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categoryandproduct.Category')),
            ],
        ),
    ]
