# Generated by Django 2.2.7 on 2019-12-24 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0003_auto_20191214_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
        migrations.CreateModel(
            name='ElectronicProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('special_price', models.FloatField()),
                ('ram', models.CharField(max_length=100)),
                ('rom', models.CharField(max_length=100)),
                ('expandable_memory', models.CharField(blank=True, max_length=100, null=True)),
                ('display_details', models.CharField(max_length=255)),
                ('processor_details', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('full_description', models.TextField(max_length=255)),
                ('sort_description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=100)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categoryandproduct.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='electronic_product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='categoryandproduct.ElectronicProduct'),
            preserve_default=False,
        ),
    ]
