# Generated by Django 2.2.7 on 2019-12-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0004_auto_20191224_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoryandproduct.Brand'),
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='sort_description',
            field=models.TextField(),
        ),
    ]
