# Generated by Django 2.2.7 on 2019-12-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0005_auto_20191224_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
