# Generated by Django 2.2.7 on 2019-12-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0006_auto_20191224_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='product_image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
