# Generated by Django 2.2.7 on 2019-12-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0008_auto_20191226_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='product_image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
