# Generated by Django 2.2.7 on 2020-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0010_electronicproduct_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='categories',
            field=models.CharField(blank=True, choices=[('mobiles', 'mobiles'), ('laptops', 'laptops'), ('tablets', 'tablets'), ('pcs', 'pcs')], max_length=20, null=True),
        ),
    ]
