# Generated by Django 2.2.7 on 2020-01-21 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0011_auto_20200107_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categoryandproduct.SubCategory')),
            ],
        ),
    ]
