# Generated by Django 2.2.7 on 2020-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetail',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
