# Generated by Django 2.2.7 on 2020-03-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryandproduct', '0012_subcategorymenu'),
        ('orders', '0002_auto_20200331_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdetail',
            name='being_delivered',
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Delivered', 'delivered'), ('Cancelled', 'Cancelled'), ('Processing', 'processing'), ('Pending', 'pending'), ('Transaction Failed', 'transaction failed')], null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrdersDetail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryandproduct.ElectronicProduct')),
            ],
        ),
    ]
