# Generated by Django 2.2.7 on 2020-03-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200331_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdetail',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='ordersdetail',
            name='received',
        ),
    ]
