# Generated by Django 2.2.7 on 2020-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200331_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'delivered'), ('Cancelled', 'Cancelled'), ('Processing', 'processing'), ('Pending', 'pending'), ('Transaction Failed', 'transaction failed')], default='Processing', max_length=20, null=True),
        ),
    ]
