# Generated by Django 2.2.7 on 2020-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200331_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'delivered'), ('Cancelled', 'Cancelled'), ('Processing', 'processing'), ('Orderd', 'Ordered'), ('Packed', 'packed'), ('Shipped', 'shipped'), ('Pending', 'pending'), ('Transaction Failed', 'transaction failed')], default='Ordered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'delivered'), ('Cancelled', 'Cancelled'), ('Processing', 'processing'), ('Orderd', 'Ordered'), ('Packed', 'packed'), ('Shipped', 'shipped'), ('Pending', 'pending'), ('Transaction Failed', 'transaction failed')], default='Processing', max_length=20, null=True),
        ),
    ]
