# Generated by Django 2.2.7 on 2020-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200401_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
