# Generated by Django 2.2.7 on 2020-04-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_delivered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='amount',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='code_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='code_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='order_above',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Processing', 'processing'), ('Ordered', 'ordered'), ('Packed', 'packed'), ('Shipped', 'shipped'), ('Pending', 'pending'), ('Transaction Failed', 'transaction failed')], default='Ordered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Processing', 'processing'), ('Ordered', 'ordered'), ('Packed', 'packed'), ('Shipped', 'shipped'), ('Pending', 'pending'), ('Transaction Failed', 'transaction failed')], default='Processing', max_length=20, null=True),
        ),
    ]
