# Generated by Django 2.2.7 on 2020-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200403_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='order_above',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
