# Generated by Django 2.2.7 on 2020-01-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200125_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='items',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_items',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
