# Generated by Django 2.2.7 on 2020-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200125_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddress',
            name='address_type',
            field=models.CharField(choices=[('h', 'Home'), ('w', 'Work')], max_length=1),
        ),
    ]
