# Generated by Django 2.2.7 on 2020-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200125_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddress',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
