# Generated by Django 2.2.7 on 2020-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200127_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddress',
            name='address_type',
            field=models.CharField(choices=[('Home', 'home'), ('Work', 'work')], max_length=10),
        ),
    ]
