# Generated by Django 2.2.7 on 2020-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200127_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
