# Generated by Django 2.2.7 on 2020-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200215_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
