# Generated by Django 2.2.7 on 2019-12-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20191214_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
