# Generated by Django 2.2.7 on 2020-01-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_subscribeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
