# Generated by Django 2.2.7 on 2020-01-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
